### ISSUE TITLE
Finding Address

### ISSUE THREAD

**Issue by lngarrett** [stefslon/esphome-thermoworks-smoke#2]
I've tried running both the 100-channel scanner as well as the 10/40/70 channel hopping version that was commented out. Both are spitting out unique addresses anytime a packet is found and I cannot seem to find a stable address or get a reading with valid probe data.

All of my readings I'm picking up have unique address and gibberish probe readings.

```Address: 6A EF 55 5B 2F  Data: 6A EF 55 5B 2F 5D 
     Probe 1: 2953.30 (alarm min: 2344.70, max: -2937.80)
     Probe 2: -93.50 (alarm min: -2376.60, max: -1901.80)
```

- Is the latest Smoke_NRF24_Address/Smoke_NRF24_Address.ino the sketch I should be using? 
- Why did you switch to scanning 100 channels vs originally hopping the FCC documented 10/40/70? 

Thanks

**Comment by stefslon** [comment]
Hey, yeah, the latest Smoke_NRF24_Address/Smoke_NRF24_Address.ino is the one I used to find the address of my Smoke unit. I switched from 10/40/70 to 100 because I wanted to see if any other channels are used. I just left it running for about 30 minutes. In the end I saw valid transmissions only on channels 10, 40 and 70. All other channels were fairly quiet.

Here is the actual output of my scanning:
```
Switching frequency: 71
Switching frequency: 70
 Data: 29 60 5D 0E 17 85 02 40 06 40 01 73 03 40 06 40 01 00 00 00 03 01 00 00 96 00 
     Probe 1: 64.50 (alarm min: 32.00, max: 160.00)
     Probe 2: 88.30 (alarm min: 32.00, max: 160.00)
 Data: 29 60 5D 0E 17 85 02 40 06 40 01 73 03 40 06 40 01 00 00 00 03 01 00 00 96 00 
     Probe 1: 64.50 (alarm min: 32.00, max: 160.00)
     Probe 2: 88.30 (alarm min: 32.00, max: 160.00)
 Data: 29 60 5D 0E 17 85 02 40 06 40 01 73 03 40 06 40 01 00 00 00 03 01 00 00 96 00 
     Probe 1: 64.50 (alarm min: 32.00, max: 160.00)
     Probe 2: 88.30 (alarm min: 32.00, max: 160.00)
 Data: 29 60 5D 0E 17 85 02 40 06 40 01 73 03 40 06 40 01 00 00 00 03 01 00 00 96 00 
     Probe 1: 64.50 (alarm min: 32.00, max: 160.00)
     Probe 2: 88.30 (alarm min: 32.00, max: 160.00)
 Data: 29 60 5D 0E 17 85 02 40 06 40 01 73 03 40 06 40 01 00 00 00 03 01 00 00 96 00 
     Probe 1: 64.50 (alarm min: 32.00, max: 160.00)
     Probe 2: 88.30 (alarm min: 32.00, max: 160.00)
 Data: 29 60 5D 0E 17 85 02 40 06 40 01 73 03 40 06 40 01 00 00 00 03 01 00 00 96 00 
     Probe 1: 64.50 (alarm min: 32.00, max: 160.00)
     Probe 2: 88.30 (alarm min: 32.00, max: 160.00)
 Data: 29 60 5D 0E 17 85 02 40 06 40 01 73 03 40 06 40 01 00 00 00 03 01 00 00 96 00 
     Probe 1: 64.50 (alarm min: 32.00, max: 160.00)
     Probe 2: 88.30 (alarm min: 32.00, max: 160.00)
Switching frequency: 69
Switching frequency: 68
Switching frequency: 67
Switching frequency: 66
Switching frequency: 65
Switching frequency: 64
Switching frequency: 63
Switching frequency: 62
Switching frequency: 61
 Data: 5A 90 12 84 53 2A 20 52 96 52 95 
     Probe 1: 823.40 (alarm min: -2731.00, max: -2705.40)
     Probe 2: -2107.20 (alarm min: -2129.00, max: -2190.60)
 Data: 54 A5 55 2A 5C AB 42 09 E9 C8 A8 AA A5 2D 
     Probe 1: 1706.70 (alarm min: -2232.80, max: -587.90)
     Probe 2: -2312.60 (alarm min: -2402.30, max: -2811.50)
Switching frequency: 60
Switching frequency: 59
Switching frequency: 58
Switching frequency: 57
Switching frequency: 56
```

Hope this helps.

**Comment by lngarrett** [comment]
OK, thanks for sanity checking the code for me - I'm not seeing anything like that at all. I'm starting to question my nrf24 now as even with a Flipper it's spitting out unique addresses and random packet lengths every time.

**Comment by stefslon** [comment]
Do you have a second nrf24 unit to test with? Or, if you have one, you can try setting up a basic sender/receiver just to make sure everything is wired correctly and you are not dealing with a faulty unit.

**Comment by lngarrett** [comment]
I did just that - I set up two completely different NRF24 modules and was able to verify they can TX/RX (the guide you linked). They were able to talk fine. However, unfortunately I'm still getting only random length packets.

Do you reliably see the Smoke every ~15 seconds? If I didn't know any better it's as if my Smoke isn't even transmitting, but I'm watching the Smoke receiver get updates every 15 seconds, so clearly it is.


```
Switching frequency: 10
Switching frequency: 40
Switching frequency: 70
Switching frequency: 10
Switching frequency: 40
Switching frequency: 70
Address: 0A 49 09 2D 20  Data: 0A 49 09 
     Probe 1: 1668.90 (alarm min: -2348.30, max: -2763.40)
     Probe 2: 873.80 (alarm min: 520.10, max: 65.70)
Address: 58 DB B5 49 53  Data: 58 DB B5 49 53 A2 A6 B6 55 55 
     Probe 1: -2287.80 (alarm min: 2184.50, max: 2194.20)
     Probe 2: -1096.60 (alarm min: 1986.10, max: 2157.70)
Switching frequency: 10
Switching frequency: 40
Switching frequency: 70
Switching frequency: 10
Switching frequency: 40
Switching frequency: 70
```

**Comment by lngarrett** [comment]
I found it! I'll contribute back a slightly more robust address finder later, but for now I just wanted to share my excitement and explain. You (or your Smoke rather) used a 0x55 preamble. I needed to us 0xAA because my MAC's first bit is a 1. From Travis Goodspeed:

```
In the case of the Nordic radios, there is no SYNC pattern unique to the radio. Instead, the MAC address itself serves this purpose. So an [OpenBeacon](http://www.openbeacon.org/) packet will begin with {0x55, 0x01, 0x02, 0x03, 0x02, 0x01} while a [Turning Point Clicker](http://travisgoodspeed.blogspot.com/2010/07/reversing-rf-clicker.html)'s packets will begin with {0x55, 0x12, 0x34, 0x56}. The preamble in this case will be 0x55 if the first bit of the SYNC/MAC is a 0 and 0xAA if the first bit is a 1. To make matters worse, the chip does not allow a MAC shorter than three bytes, so previously it was believed that at least so many bytes of the destination address must be known in order to receive a packet with this chip.
```

So, a more robust scanner should try both. I don't think it necessary to even hop 10/40/70 - the transmitter already broadcasts all three. It would just help with interference I suppose.

Thanks for your help. I'll share my project once I've completed it. I was stuck on step 0 :) 

Edit: Actually, ESPHome seems like a much better fit than what I was planning. I just used your complete solution. Thanks again.

**Comment by lngarrett** [comment]
Added changed in #3

**Comment by stefslon** [comment]
Great find!! Thanks for the updates.
